---
title: '6\. Worksheet: Diversity Sampling'
author: "Brianna Crawley; Z620: Quantitative Biodiversity, Indiana University"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

In this worksheet, you will use the jelly bean site-by-species matrix generated from **6. Diversity Sampling**.
Along with tools outlined in the **5. Local (alpha) Diversity** and **7. Control Structures** handouts, you will develop questions, visualize data, and test hypotheses related to sampling effects and its effect on estimates of within-sample biodiversity. 


## Directions:
1. In the Markdown version of this document in your cloned repo, change "Student Name" on line 3 (above) to your name.
2. Complete as much of the worksheet as possible during class.
3. Refer to previous handout to help with developing of questions and writing of code.
4. Answer questions in the  worksheet.
Space for your answer is provided in this document and indicated by the ">" character.
If you need a second paragraph be sure to start the first line with ">".
You should notice that the answer is highlighted in green by RStudio (color may vary if you changed the editor theme).
5. Before you leave the classroom, **push** this file to your GitHub repo.
6. For the assignment portion of the worksheet, follow the directions at the bottom of this file. 
7. When you are done, **Knit** the text and code into a PDF file.
8. After Knitting, submit the completed exercise by creating a **pull request** via GitHub.
Your pull request should include this file `6.DiversitySampling_Worskheet.Rmd` and the PDF output of `Knitr` (`DiversitySampling_Worskheet.pdf`).


## 1) Group brainstorming 

With your team partner and perhaps other students in the class, spend 15 minutes or so brainstorming questions, code, "fantasy figures", and statistical tests that could be used to test questions with the class's data represented in the site-by-species matrix that you have generated. 

## 2) Code

Use the space below for code that is being used to analyze your data and test your hypotheses. 
Create one (and only one, although it can have multiple panels) *publication quality* figure. 
Make sure to annotate your code using # symbols so others (including instructors) understand what you have done and why you have done it. 

```{r}
require(vegan) #loads the package 'vegan'
jellybean <- read.table("JellyBeans.txt", sep = "\t", header = TRUE) #load the dataset
jellybean.num <- jellybean[ , 3:30] #index columns that contain numeric data
S.obs <- function (x=""){
  rowSums(x>0) * 1
  }
#defines S.obs as function that calculates observed species richness

S.obs(jellybean.num) #calculates observes species richness for jellybean dataset
C  <- function(x = ""){
   1 - (rowSums(x==1) / rowSums(x))
   }
#defines C as function that calculates coverage
C(jellybean.num) #calculates coverage for jellybean dataset

SimpD <- function (x =""){
  D = 0
  N = sum(x)
  for (n_i in x){
    D = D + (n_i^2) / (N^2)
  }
  return(D)
}
#defines SimpD as function that calculates Simpson's diversity index
SimpD(jellybean.num) #calculates Simpson's diversity of jellybean data
RACresults <- radfit(jellybean.num) #generates rank abundance curves for each site and fits one of five species abundance models to each curve
plot.new()
plot(RACresults, las = 1, cex.lab = 1.4, cex.axis = 1.25)
```


## 3) Figure caption 

Write an informative yet succinct (~5 sentences) caption that creates a "stand-alone" figure. 
Take a peek at figures and figure captions in a paper published in your favorite journal for inspiration.

Figure 1. Species abundance curves for nine samples of jellybeans. Rank indicates the abundance of the species in comparison to others, while abundance indicates the number of individuals per species. Samples vary in evenness.

## SUBMITTING YOUR ASSIGNMENT
Use Knitr to create a PDF of your completed 6.DiversisitySampling_Worksheet.Rmd document, push it to GitHub, and create a pull request.
Please make sure your updated repo includes both the pdf and RMarkdown files.

Unless otherwise noted, this assignment is due on **Wednesday, January 30^th^, 2017 at 12:00 PM (noon)**.